name: CI - local self-hosted build & compose
on:
  push:
    branches: [ main ]

jobs:
  build-and-up:
    runs-on: [self-hosted, windows]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show runner info
        shell: powershell
        run: |
          whoami
          Write-Output "OS Info:"
          Get-CimInstance Win32_OperatingSystem | Select-Object Caption, Version, OSArchitecture
          
          # Verifica Docker
          try {
              docker --version
          } catch {
              Write-Output "Docker not installed"
              exit 1
          }

      - name: Build images and start containers
        shell: powershell
        run: |
          Write-Output "Building and starting containers..."
          docker compose -f "$Env:GITHUB_WORKSPACE\..\docker-compose.dev.yml" up -d --build --remove-orphans

      - name: Show containers
        shell: powershell
        run: |
          docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}"
